apiVersion: v1
kind: Service
metadata:
  name: sgdtr-backend-service
spec:
  type: NodePort
  selector:
    app: sgdtr-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
